---
name: pkgcheck

on:
  schedule:
    - cron: '1 23 * * *'
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run pkgcheck
        uses: pkgcore/pkgcheck-action@v1